version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Madrid"
    target-branch: "main"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Madrid"
    target-branch: "main"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    groups:
      androidx:
        patterns:
          - "androidx.*"
        update-types:
          - "minor"
          - "patch"
      kotlin-and-ksp:
        patterns:
          - "org.jetbrains.kotlin*"
          - "org.jetbrains.kotlinx*"
          - "com.google.devtools.ksp"
        update-types:
          - "minor"
          - "patch"
